### ISSUE TITLE
Source locations are specified in normalized coords?

### ISSUE THREAD

**Issue by behdad** [notofonts/noto-cjk-varco#13]
For other rcjk fonts I have used my varc-rcjk tool on, the source locations are specified in user coordinates. But looks like in this project the source locations are specified in normalized coordinates. This is tripping off my tools. Which one is correct?

Eg. glyph uni4E48 us two sources, one at `()`, and other at `(('wght', 1.0),)`, whereas the axes are `{'wght': (100.0, 100.0, 900.0)}`.

**Comment by justvanrossum** [comment]
The (global) axis objects have a mapping attribute, that provide avar-style mapping. This font was originally imported from a TTF, and on import, Fontra created the mapping from user to source coordinates, which were normalized in the TTF. This is the axis definition:
```json
{
  "axes": [
    {
      "tag": "wght",
      "name": "wght",
      "label": "wght",
      "hidden": false,
      "mapping": [
        [
          200,
          0
        ],
        [
          300.018310546875,
          0.094970703125
        ],
        [
          399.993896484375,
          0.21002197265625
        ],
        [
          500.01220703125,
          0.3599853515625
        ],
        [
          599.98779296875,
          0.510009765625
        ],
        [
          700.006103515625,
          0.72998046875
        ],
        [
          900,
          1
        ]
      ],
      "maxValue": 900,
      "minValue": 200,
      "defaultValue": 200
    }
  ]
}
```

You should be able to find the mapping as `.mapping` on the axis object, as obtained via `backend.getGlobalAxes()`.

**Comment by behdad** [comment]
Thanks.

**Comment by behdad** [comment]
Right now I'm using `rcjkfont.designspace["axes"]`; do you suggest I use `rcjkfont.backend.getGlobalAxes()` then?

**Comment by justvanrossum** [comment]
Yes. In hindsight, `.designspace` should be private, it contains a raw dict. The `getGlobalAxes()` call will give you proper objects. (This is generally the case with Fontra backend objects: you should ideally only access data via methods.)
